export const RISK_REASON_CODES = {
  CATASTROPHIC_ROOT_DESTRUCTION: 1001,
  PROTECTED_SYSTEM_TREE_DESTRUCTION: 1002,
  BROAD_UNRESOLVED_CATASTROPHIC_DELETE: 1003,
  RAW_BLOCK_DEVICE_WRITE: 1011,
  OPAQUE_LOCAL_DESTRUCTIVE_SELECTION: 1012,
  SPECIAL_DEVICE_SIDE_EFFECT: 1013,

  AFFECTED_FILE_COUNT_CRITICAL: 2001,
  AFFECTED_FILE_COUNT_RISKY: 2002,
  CONDITIONAL_AFFECTED_FILE_COUNT: 2003,
  SENSITIVE_EXTENSION: 2011,
  CONDITIONAL_SENSITIVE_EXTENSION: 2012,
  AFFECTED_TOTAL_SIZE: 2021,
  CONDITIONAL_AFFECTED_TOTAL_SIZE: 2022,
  OLD_AFFECTED_FILE: 2031,
  CONDITIONAL_OLD_AFFECTED_FILE: 2032,

  GIT_WORKTREE_DISCARD: 3001,

  EXTERNAL_RESOURCE_DESTRUCTION: 4001,
  CONTAINER_HOST_WRITE_EXPOSURE: 4002,
} as const;

export type ReasonCode = typeof RISK_REASON_CODES[keyof typeof RISK_REASON_CODES];
export type ReasonSeverity = 'risky' | 'critical';

export const DIRECT_REASON_CODES = [
  RISK_REASON_CODES.CATASTROPHIC_ROOT_DESTRUCTION,
  RISK_REASON_CODES.PROTECTED_SYSTEM_TREE_DESTRUCTION,
  RISK_REASON_CODES.BROAD_UNRESOLVED_CATASTROPHIC_DELETE,
  RISK_REASON_CODES.RAW_BLOCK_DEVICE_WRITE,
  RISK_REASON_CODES.OPAQUE_LOCAL_DESTRUCTIVE_SELECTION,
  RISK_REASON_CODES.SPECIAL_DEVICE_SIDE_EFFECT,
  RISK_REASON_CODES.GIT_WORKTREE_DISCARD,
  RISK_REASON_CODES.EXTERNAL_RESOURCE_DESTRUCTION,
  RISK_REASON_CODES.CONTAINER_HOST_WRITE_EXPOSURE,
] as const;

export type DirectRiskCode = typeof DIRECT_REASON_CODES[number];

export const DIRECT_RISK_POLICY: Readonly<Record<DirectRiskCode, ReasonSeverity>> = {
  [RISK_REASON_CODES.CATASTROPHIC_ROOT_DESTRUCTION]: 'critical',
  [RISK_REASON_CODES.PROTECTED_SYSTEM_TREE_DESTRUCTION]: 'critical',
  [RISK_REASON_CODES.BROAD_UNRESOLVED_CATASTROPHIC_DELETE]: 'critical',
  [RISK_REASON_CODES.RAW_BLOCK_DEVICE_WRITE]: 'critical',
  [RISK_REASON_CODES.OPAQUE_LOCAL_DESTRUCTIVE_SELECTION]: 'risky',
  [RISK_REASON_CODES.SPECIAL_DEVICE_SIDE_EFFECT]: 'risky',
  [RISK_REASON_CODES.GIT_WORKTREE_DISCARD]: 'risky',
  [RISK_REASON_CODES.EXTERNAL_RESOURCE_DESTRUCTION]: 'risky',
  [RISK_REASON_CODES.CONTAINER_HOST_WRITE_EXPOSURE]: 'risky',
};

export const REASON_CODE_SEVERITY: Readonly<Record<ReasonCode, ReasonSeverity>> = {
  ...DIRECT_RISK_POLICY,
  [RISK_REASON_CODES.AFFECTED_FILE_COUNT_CRITICAL]: 'critical',
  [RISK_REASON_CODES.AFFECTED_FILE_COUNT_RISKY]: 'risky',
  [RISK_REASON_CODES.CONDITIONAL_AFFECTED_FILE_COUNT]: 'risky',
  [RISK_REASON_CODES.SENSITIVE_EXTENSION]: 'critical',
  [RISK_REASON_CODES.CONDITIONAL_SENSITIVE_EXTENSION]: 'risky',
  [RISK_REASON_CODES.AFFECTED_TOTAL_SIZE]: 'critical',
  [RISK_REASON_CODES.CONDITIONAL_AFFECTED_TOTAL_SIZE]: 'risky',
  [RISK_REASON_CODES.OLD_AFFECTED_FILE]: 'critical',
  [RISK_REASON_CODES.CONDITIONAL_OLD_AFFECTED_FILE]: 'risky',
};

export function normalizeReasonCodes(codes: Iterable<ReasonCode>): ReasonCode[] {
  return [...new Set(codes)].sort((left, right) => left - right);
}
